### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hiringManager** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#1]
Is this specifically for Catalina or High Sierra? Thanks.

**Comment by dps-910** [comment]
> Is this specifically for Catalina or High Sierra? Thanks.

This should work for all versions of macOS, but I am not sure about Big Sur. It should work for every other version of macOS though.

**Comment by hiringManager** [comment]
Thanks man. Your config saved me a lot of time! Literally copy/paste then the 7010 I have is ready. Still can't get audio working outside of HDMI, but I'll figure it out. 

Any additional recommendations on post-install?

**Comment by dps-910** [comment]
> Thanks man. Your config saved me a lot of time! Literally copy/paste then the 7010 I have is ready. Still can't get audio working outside of HDMI, but I'll figure it out.
> 
> Any additional recommendations on post-install?

you're welcome :)

**Comment by hiringManager** [comment]
Hi again, feel free to delete this thread btw. 

Were you able to fix audio issues in last commit? 

Anyway, I wanted you to know that I'm sharing your efi on a youtube video I made. If that's alright with you, I'll leave it up. Thanks again!

https://youtu.be/8nqQ3FL4uW8

**Comment by dps-910** [comment]
> Hi again, feel free to delete this thread btw. 
> 
> Were you able to fix audio issues in last commit? 
> 
> Anyway, I wanted you to know that I'm sharing your efi on a youtube video I made. If that's alright with you, I'll leave it up. Thanks again!
> 
> https://youtu.be/8nqQ3FL4uW8

Yeah audio is fixed and working :) only things that don't work is sleep I could probably fix that though.

**Comment by hiringManager** [comment]
Awesome man! Appreciate it.
