### ISSUE TITLE
Troubleshooting Monterey OCLP

### ISSUE THREAD

**Issue by gatorback** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#11]
Greetings David, 

I was able to install Monterey to an SSD, install OCLP, disable SIP, and boot it up on a 10th gen CPU.   The goal is configure said SSD for an Optipelx 7010.   I tried to boot the Monterey SSD via OC, but was met with the error in the photos: 

https://photos.app.goo.gl/rksaCGDHycmnGWqq6

Is this enough information to diagnose the issue?  If you are open to messaging on Telegram, I am gatorback94

**Comment by dps-910** [comment]
I would recommend putting the SSD into the Optiplex 7010 and just doing the install on that. You could also check the Hackintosh discord, they may be able to help you with things! 

Sorry for not getting back sooner, havn't been on this github in a long time .
