### ISSUE TITLE
can we upgrade to sonoma?

### ISSUE THREAD

**Issue by fishersyu** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#14]

**Comment by dps-910** [comment]
You could, possibly. There are issues with no AVX2 support, but you could possibly work around it by installing cryptex manually https://github.com/dortania/OpenCore-Legacy-Patcher/issues/998#issuecomment-1163607808

Last time I tried this, I managed to boot into Sonoma, but it wouldn't let me get past the Privacy part, it just loaded infinitely.
I would recommend buying a newer PC if you could, or trying the manual method, but no guarentees that it will work.
