### ISSUE TITLE
[SOLVED] I cannot get this to work - I am getting Critical errors

### ISSUE THREAD

**Issue by bearhntr** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#15]
I used the same process as here:    https://i12bretro.github.io/tutorials/0607.html

To build a completely new Flash drive - and then followed your steps to make it 'Monterey'.  I know I should not have assumed, but your steps do not state otherwise.  😥   Should I be doing something else?  I either get some kind of 'critical error' on boot - or I get to the "Reinstall macOS Monterey" option and am told "Installation could not continue.  Installation requires downloading important content.  That content can't be downloaded at this time.  Try again later"  --  I have verified I have Internet access. 

I have a Desktop Optiplex 7010 and would love to put Monterey on it, as Big Sur is kinda old.  I take it that Sonoma will not work?  

I have discovered that you cannot use the entire disk when you install the Big Sur per the link above.  This computer has a 240GB SSD and if I try and use full disk it gets to a point and just reboots over and over and over - never installs completely.  If I adjust the partition when I erase the disk to only be 200GB I have no issues.  I also discovered you cannot adjust this after installation (or at least I could not).  

I figured out how to save the INSTALLER.LOG - no idea what any of it means (attaching here). 

[Installer Log 17-Dec-2023.txt](https://github.com/dav1dnix/Dell-Optiplex-7010-Hackintosh-OpenCore/files/13697749/Installer.Log.17-Dec-2023.txt)

**Comment by bearhntr** [comment]
I got it working - finally.  I just keep booting and booting an booting - sometimes had to had power OFF the 7010 to get it to continue.

**Comment by dps-910** [comment]
It should be working. I updated the EFI recently. Sorry for not getting back for ages. I havnt been on this account in a while.

I don't do hackintosh much on this PC anymore
