### ISSUE TITLE
POST INSTALL and OCLP

### ISSUE THREAD

**Issue by bearhntr** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#17]
I finally got Monterey installed on the Core i5 Optiplex 7010 DT machine (yes it has Intel HD4000 GPU on the processor).  I have tried to do the POST INSTALL steps...and no issues rebooting into Recovery Mode - and I can run the two commands.  But, how do I download and run the OCLP (GUI tool)?  I tried running it from the desktop after making the changes - but, apparently they do not survive a reboot to get out of Recovery Mode.

**Comment by dps-910** [comment]
I'm unsure, OCLP should run just fine. I'm not sure what you mean.
