### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by hiringManager** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#2]
Taken the leap/successfully upgraded yet? Not using it myself, but I will probably create a guide to updating to it. 

Thanks!

**Comment by dps-910** [comment]
> Taken the leap/successfully upgraded yet? Not using it myself, but I will probably create a guide to updating to it. 
> 
> Thanks!

I haven't upgraded to it yet. I might do in the future, but apparently HD 4000 graphics is not supported, though I have seen that it is possible. I think that support will be removed in later updates, so I will wait a bit longer before updating I think and see if Apple keep support for the HD 4000 or not.

**Comment by dps-910** [comment]
> > Taken the leap/successfully upgraded yet? Not using it myself, but I will probably create a guide to updating to it. 
> > 
> > Thanks!
> 
> I haven't upgraded to it yet. I might do in the future, but apparently HD 4000 graphics is not supported, though I have seen that it is possible. I think that support will be removed in later updates, so I will wait a bit longer before updating I think and see if Apple keep support for the HD 4000 or not.

Maybe I could install on another partition to try it out. I don't want to mess up my current macos install.

**Comment by hiringManager** [comment]
Alright, I've toyed with it a bit at this point, but haven't really been able to understand my problems with it due to the fact that it's having issues mid-install. I'll need to buy a new SSD before I can proceed, because apfs gets so angry about being repartitioned. 

I'll keep you posted if I'm successful.

**Comment by dps-910** [comment]
> Alright, I've toyed with it a bit at this point, but haven't really been able to understand my problems with it due to the fact that it's having issues mid-install. I'll need to buy a new SSD before I can proceed, because apfs gets so angry about being repartitioned.
> 
> I'll keep you posted if I'm successful.

I have updated my EFI, I just changed the SMBIOS from iMac13,1 to iMac14,4. Big Sur is working quite well.

**Comment by dps-910** [comment]
> > Alright, I've toyed with it a bit at this point, but haven't really been able to understand my problems with it due to the fact that it's having issues mid-install. I'll need to buy a new SSD before I can proceed, because apfs gets so angry about being repartitioned.
> > I'll keep you posted if I'm successful.
> 
> I have updated my EFI, I just changed the SMBIOS from iMac13,1 to iMac14,4. Big Sur is working quite well.

If everything has worked I will close the issue, if not could you let me know and I will try and help you

**Comment by hiringManager** [comment]
I'm not sure honestly. I'm about 7 hours in, and still having a lot of issues. Managed to install catalina again, upgrade failed. Couldn't build the installer from osx, and battled it in Linux. It's been a whole situation, and I don't even want it installed. It's just such a challenge. Main issue is that I keep running into boot loops after doing recovery>boot into installer, and I have no idea why tbh. I'm dealing with far too many variables.

Next plan is to (since I have a hackintosh laptop as of 3 days ago)

Build Big Sur installer in OSX Catalina if possible
Copy your EFI to a usb
Chain load into it with opencore
Pray. 

My biggest question I guess is that, When you successfully installed it, can you walk me through the process of making the usb so I can rule things out? Did you skip recovery, etc. 

If this doesn't work, I'm booting into QEMU I guess and attempting from there.

**Comment by dps-910** [comment]
> 
> 
> I'm not sure honestly. I'm about 7 hours in, and still having a lot of issues. Managed to install catalina again, upgrade failed. Couldn't build the installer from osx, and battled it in Linux. It's been a whole situation, and I don't even want it installed. It's just such a challenge. Main issue is that I keep running into boot loops after doing recovery>boot into installer, and I have no idea why tbh. I'm dealing with far too many variables.
> 
> Next plan is to (since I have a hackintosh laptop as of 3 days ago)
> 
> Build Big Sur installer in OSX Catalina if possible
> Copy your EFI to a usb
> Chain load into it with opencore
> Pray.
> 
> My biggest question I guess is that, When you successfully installed it, can you walk me through the process of making the usb so I can rule things out? Did you skip recovery, etc.
> 
> If this doesn't work, I'm booting into QEMU I guess and attempting from there.

I upgraded from Catalina using [gibMacOS](https://github.com/corpnewt/gibMacOS), then I followed [this](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#extracting-the-installer) to extract the installer and install Big Sur.
Before I did this, I made sure to update the EFI to OpenCore 0.6.3 (download my EFI and just put the BOOT and OC folders in your EFI partition and it should work).

**Comment by dps-910** [comment]
> Next plan is to (since I have a hackintosh laptop as of 3 days ago)

This EFI is for Dell Optiplex 7010 desktops with the Ivy Bridge processor, not laptops.

**Comment by hiringManager** [comment]
> > Next plan is to (since I have a hackintosh laptop as of 3 days ago)
> 
> This EFI is for Dell Optiplex 7010 desktops with the Ivy Bridge processor, not laptops.

Oh I'm aware. This is for a 7010 MT and SFF. My laptop is clover and not OC. 

I'll continue working on it over the next few days, and try the process through Catalina in this manner instead. Each install is taking me a while, so I'll keep you posted. Thanks for the help!

**Comment by hiringManager** [comment]
I'll be honest, I spent many more hours on it today. Had about 5 failed installs, a corrupted cmos, then it was able to get to a black screen with a cursor. Ended up messing around with the igpu variable, and managed to get to a desktop. GPU accel is broken right now, but that may be due to the fact that my mbx bios dealie is locked out... But mission accomplished I guess. Still have no idea why it took so many tries with almost nothing changing. 

Really Bizarre.

**Comment by hiringManager** [comment]
Okay, discovered the culprit (and you may want to add this to doc). 

So, I was doing this on my second Optiplex, and the install kept dying as I stated. The reason for this is actually the fact that the i7 3470 uses Intel HD Graphics 2500 instead of 4000. Since I was unable to get any verbose output, and it was right at the end of the init, I had no idea that this was the culprit. The way that I completed the first install was simply by moving to my rig with a dGPU, then I could use Big Sur on the HD 2500 one, but only after completing install. Albeit, no GPU accel since it isn't supported. 

I copied the empty framebuffer of 0x01620007, and only by doing so was I able to complete the install on my next attempt. But, milage varies of course.

**Comment by fercata** [comment]
> > Muy bien, he jugueteado un poco con él en este momento, pero realmente no he podido entender mis problemas con él debido al hecho de que está teniendo problemas a mitad de la instalación. Necesitaré comprar una nueva SSD antes de poder continuar, porque apfs se enoja mucho por ser reparticionado. > > Te mantendré informado si tengo éxito. > > He actualizado mi EFI, acabo de cambiar el SMBIOS del iMac13,1 al iMac14,4. Big Sur está funcionando bastante bien. 


Hello, my English is bad, sorry, I have optiplex SFF 7010 with big sur and I can't get the audio to work, I use clover, can you help me please

**Comment by fercata** [comment]
> > Next plan is to (since I have a hackintosh laptop as of 3 days ago)
> 
> This EFI is for Dell Optiplex 7010 desktops with the Ivy Bridge processor, not laptops.
How can I contact you?

**Comment by dps-910** [comment]
> 
> 
> > > Muy bien, he jugueteado un poco con él en este momento, pero realmente no he podido entender mis problemas con él debido al hecho de que está teniendo problemas a mitad de la instalación. Necesitaré comprar una nueva SSD antes de poder continuar, porque apfs se enoja mucho por ser reparticionado. > > Te mantendré informado si tengo éxito. > > He actualizado mi EFI, acabo de cambiar el SMBIOS del iMac13,1 al iMac14,4. Big Sur está funcionando bastante bien.
> 
> Hello, my English is bad, sorry, I have optiplex SFF 7010 with big sur and I can't get the audio to work, I use clover, can you help me please

You should really use OC and then it will work properly. If you clone my repo and then make an opencore USB but replace everything in the EFI folder with whats on my repo. I use OC 0.7.2, but you can try the latest and it may work.

I'm not sure about clover as I don't use it. But you could try this maybe https://www.reddit.com/r/hackintosh/comments/4e23w6/guide_native_audio_with_clover_applealckext/ I'm not sure if it would work. It's worth trying though. Good that you got clover working though :)

**Comment by dps-910** [comment]
> 
> 
> Okay, discovered the culprit (and you may want to add this to doc).
> 
> So, I was doing this on my second Optiplex, and the install kept dying as I stated. The reason for this is actually the fact that the i7 3470 uses Intel HD Graphics 2500 instead of 4000. Since I was unable to get any verbose output, and it was right at the end of the init, I had no idea that this was the culprit. The way that I completed the first install was simply by moving to my rig with a dGPU, then I could use Big Sur on the HD 2500 one, but only after completing install. Albeit, no GPU accel since it isn't supported.
> 
> I copied the empty framebuffer of 0x01620007, and only by doing so was I able to complete the install on my next attempt. But, milage varies of course.

Sorry for my (very late) response. I'm not active much on here. I initially made this repository under the assumption that people would have the same processor, but it's great that people are getting it to work anyway.
Also I would recommend switching to OC. You can replace everything in EFI with my EFI when you make the usb installer.
Also I will add supported intel HD graphics to the README :).
