### ISSUE TITLE
wifi is not working how to make it work i have a dongle

### ISSUE THREAD

**Issue by Aditya753b** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#4]

**Comment by dps-910** [comment]
It depends what sort of wifi dongle you have. If the manufacturer has a kext for it, you could put that in the kexts folder, or install their software. What manufacturer is it? They may or may not have one for macOS, it would be a good idea to ask in Hackintosh discord though https://discord.com/invite/8aKs69x
