### ISSUE TITLE
Blackscreen after OpenCore picker

### ISSUE THREAD

**Issue by V3ntus** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#6]
System info:
i5-3470
GT 1030

Process:
- ran gibMacOS MakeInstall.bat with OpenCore selection
- ran OpenCore's `./macrecovery.py -b Mac-E43C1C25D4880AD6 -m 00000000000000000 download` and moved BaseSystem.dmg to the USB (so, online recovery install)
- replaced files on USB with your repo (did not copy the root config.plist from [this commit](https://github.com/dps910/Dell-Optiplex-7010-Hackintosh-OpenCore/commit/fe6e10493db604552920c72470dd30ff482e5d87), but I *did* append the `-v` boot arg in the config and added my language)

Please update which "guide" to follow. I'm assuming [Dortania's OpenCore install guide](https://dortania.github.io/OpenCore-Install-Guide/)?

I did review my BIOS options. I would assume the verbose flag would show something if it attempted to boot the BaseSystem, but that is not the case. I'm assuming the Nvidia card may be the culprit so I'll continue to experiment and update if needed

Edit 1: No support for GT1030 since High Sierra. But even removing the card from my system produces no change in behavior

**Comment by dps-910** [comment]
I did follow the Dortania guide that you linked to create the config.plist. To install macOS I use this https://github.com/corpnewt/gibMacOS the gibMacOS.command and MakeInstall.py. Then I replace everything in the USB EFI with everything in my repo. Try that and see if it works for you.
The GT 1030 could be a problem as I only have iGPU. Try unplugging it and see how it goes. If you still have black screen let me know.

**Comment by V3ntus** [comment]
@dps910 Looks like it's a problem with Big Sur, but unfortunately I was getting same results with Catalina. Right now, I'm attempting to install Mac OS in a Windows VM to create install media through that. I'll update you if I find a working process
