### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by timmujapan** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#8]
I got USB3 and sleep working perfectly with Big Sur+OC+Dell Optiplex 7010 i7-3770 with the attached EFI.  I haven't gotten the system to work, however, after I upgrade to Monterey and put the patches in for HD4000.  Tried Chris1111 and OCLP, but I will try your EFI and method next.  Thanks. 
[EFI.zip](https://github.com/dav1dnix/Dell-Optiplex-7010-Hackintosh-OpenCore/files/8220474/EFI.zip)

**Comment by sryanyuan** [comment]
I fixed the usb3 problem by generating the SSDT-HPET and adding the SSDT-XOSI (_OSI to XOSI)，but still freezes after sleeping. Can you share your solution for the sleep problem? thanks

**Comment by timmujapan** [comment]
I briefly compared the EFI that I uploaded above (EFI zip) with the main one on this GitHub post.  There are many differences, so I'm not sure which differences will affect sleep. Maybe @dav1dnix knows the answer???? My ACPI patching data near the top at the EFI is very different.  It might be (?) connected to that. what is the merit of the ACPI patching for Q11, Q12 stuff?  What does that do?

I was having freeze after sleep issues with Big Sur on the Optiplex 7010, and the problem for me was that I was using an HDMI splitter.  When I removed the splitter and just connected Optiplex DisplayPort<>HDMI monitor directly (no splitter in between), the freeze problem went away.  You might need a different displayport<>HDMI cable, a different DisplayPort<>Displayport cable, or try a different monitor.  You can try my EFI above, and see if yours will boot and wake from sleep.  You need to enter new serial numbers, though. I am using SMBIOS macpro6,1 on the EFI above.

If you are using DisplayPort cable with an adapter on the end for HDMI, that might be causing the freeze after wake from sleep.  One cable: displayport<>HDMI , no adapters or splitters in the connection solved the problem for me.

I upgraded from Big Sur to Monterey, but when I try to patch for the graphics, the machine stops booting and goes to recovery.  Maybe this is because I did an upgrade instead of a clean install. I will try clean install tomorrow.

**Comment by timmujapan** [comment]
Err!  I also should mention that the EFI that I uploaded above is working for Big Sur.  It hasn't undergone SIP modifications for Monterey.

**Comment by sryanyuan** [comment]
Thanks for your replying. I have the same ACPI patching as your EFI (Based on the dav1dnix's), which fixed the usb3.0 problem. I'll use the EFI you uploaded above to see it if it can solve the sleep issue.

**Comment by timmujapan** [comment]
The EFI I uploaded above works perfectly with sleep and USB 3 for a Dell Optiplex 7010 i7-3770 DESKTOP form factor on BIG SUR.  I think that @dav1dnix is still using the USBinjectALL kext.  The EFI I uploaded is using USBports kexts, which have the ports mapped for an Optiplex 7010 desktop. A few ports in the back have been disabled, because there are too many on this machine for macOS.  Make sure to reset the NVRAM if you want to try out this EFI...

  Have you gotten Monterey to work on this machine?  I don't have the Q11,Q12 ACPI patching in my EFI, and I'm not sure what it is for.  I hope that @dav1dnix can tell me...

**Comment by sryanyuan** [comment]
I used your EFI, but still freeze after sleep. Finally i generate a new SSDT-EC.aml with acpidump.efi, replaced the old one, it seems fixed the sleep issue.

**Comment by timmujapan** [comment]
I also had an interesting experience.... I used Dav1dnix's plist "A config. plist" below and Monterey will boot fine after root patching for HD 4000 graphics... My original one "B config.plist"--the Monterey system won't boot after the HD4000 root patching....

  :
[A config.plist-works with Monterey and patched HD4000.zip](https://github.com/dav1dnix/Dell-Optiplex-7010-Hackintosh-OpenCore/files/8230394/A.config.plist-works.with.Monterey.and.patched.HD4000.zip)
[B config.plist-Monterey crashes after graphics are patched.zip](https://github.com/dav1dnix/Dell-Optiplex-7010-Hackintosh-OpenCore/files/8230419/B.config.plist-Monterey.crashes.after.graphics.are.patched.zip)
)

B Config.plist comes from the original efi that I posted above.  It works great with big sur and can install Monterey, but won’t boot after the patches are applied…. I wonder what the reason is... If anyone knows, please teach me.… what do I need to change in my config plist or efi to get Monterey to boot after patches are applied……..

**Comment by timmujapan** [comment]
> I used your EFI, but still freeze after sleep. Finally i generate a new SSDT-EC.aml with acpidump.efi, replaced the old one, it seems fixed the sleep issue.

BTW- did you reset the nvram before you booted with my efi?  You have to do that to get fresh configurations in there…..

**Comment by sryanyuan** [comment]
> > I used your EFI, but still freeze after sleep. Finally i generate a new SSDT-EC.aml with acpidump.efi, replaced the old one, it seems fixed the sleep issue.
> 
> BTW- did you reset the nvram before you booted with my efi? You have to do that to get fresh configurations in there…..

yes, i reset the nvram before using it. after that, i replaced the old SSDT-EC.aml with my new generated one, the sleep issue not happen until now

**Comment by GuaiYiHu** [comment]
> > > I used your EFI, but still freeze after sleep. Finally i generate a new SSDT-EC.aml with acpidump.efi, replaced the old one, it seems fixed the sleep issue.
> > 
> > 
> > BTW- did you reset the nvram before you booted with my efi? You have to do that to get fresh configurations in there…..
> 
> yes, i reset the nvram before using it. after that, i replaced the old SSDT-EC.aml with my new generated one, the sleep issue not happen until now

Can you share your efi, plz, I just suffered a lot from the sleep promblem

**Comment by sryanyuan** [comment]
> > > > I used your EFI, but still freeze after sleep. Finally i generate a new SSDT-EC.aml with acpidump.efi, replaced the old one, it seems fixed the sleep issue.
> > > 
> > > 
> > > BTW- did you reset the nvram before you booted with my efi? You have to do that to get fresh configurations in there…..
> > 
> > 
> > yes, i reset the nvram before using it. after that, i replaced the old SSDT-EC.aml with my new generated one, the sleep issue not happen until now
> 
> Can you share your efi, plz, I just suffered a lot from the sleep promblem

https://github.com/sryanyuan/dell-7010usff-efi

just works for me, you can try it
