### ISSUE TITLE
EFI / config plist for Monterey

### ISSUE THREAD

**Issue by timmujapan** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#9]
@dav1dnix !

Thank you for all of your great work.  Could you please tell me what is the salient feature of your Monterey EFI or config plist that enables you to boot Monterey on the 7010 after the graphics have been patched?  I followed the Dortania guide, and I have a great EFI for the 7010 and Big Sur that works perfectly.  My EFI will also install Monterey on the 7010, but it fails to boot Monterey after the graphics have been patched.  I understand the SIP and boot args changes that need to be made, but which other config plist changes gave you the power to boot Monterey with patched graphics on the 7010?  There are so many customizations in your config plist.  I am not sure which one is important for booting Monterey with patched graphics.  I want to learn.

**Comment by dps-910** [comment]
Things should be alright now, I have updated the EFI to the latest opencore recently
